### ISSUE TITLE
Upload Smalltalk solution to Exercism

### ISSUE THREAD

**Issue by samWson** [exercism/pharo#6]
### User Story
As a user I want to:
- Upload my solution to a exercise using the Exercism command line client
- See my solution on the Exercism webpage for the solved exercise

### Summary

For additional background information and examples, see this [comment](https://github.com/exercism/pharo/issues/1#issuecomment-396878025) on issue #1.

This is one of the major challenges this language track faces on the road to launch. The code for a solution has to be extracted from a Smalltalk image and placed in a text file ready to be uploaded to Exercism. Once on Exercism it must be displayed for ease of readability without any extra machine readable artifacts or metadata. To allow for the solution to be downloaded and added to a Smalltalk image, it is highly desirable that the original file of extracted code be kept.

### Possible Solution

At the moment it is looking like the solution will follow this approximate path:
1. File out the solution code from the Smalltalk image (already a built in feature)
2. Upload the solution text file to Exercism using the existing command line tool
3. Make two copies of the solution file
4. Retain one copy as an unaltered original (this can be filed back into a Smalltalk image once downloaded)
5. Strip machine readable artifacts and meta data from the second file leaving only source code
6. Display the source code on Exercism as the solution to the exercise 

Note this is a _possible_ solution, not the only solution.

### Alternative Solutions
Pharo's native Git client, Iceberg, can also be used to extract text files, as git is used for versioning plain text files. Managing a git repository, even locally, would require more steps than filing out a file. My own personal experience with Iceberg has been painful, however it is used for development of Pharo so there are likely people who know how to get the best out of it.
Tonel is a new human readable file format for Smalltalk code, for better integration with version control software than the current Filetree format. Several Pharo community members have pointed me toward Tonel as a possible solution.

### Todo
- [ ] ~Create a solution for striping meta data out of a solution file before it is displayed on Exercism~
- [x] Investigate how to integrate these steps into Exercisms existing tool chain
- [x] Investigate if configuration of the _file out_ location can be done as a first time installation step of Pharo
- [x] Explore Tonel as an alternative human readable format
- [ ] ~Find out how to set Pharo's default _file out_ location to the `$HOME/exercisim/pharo/<exercise>` directory~

**Comment by kytrinyx** [comment]
Sweet!

I think it makes sense to have this in the Exercism repo! I've made a repository called `pharo-tooling`, and given you admin on the repo (I think that means you can edit the name of the repo, but if not, just tell me what you want it to be called). https://github.com/exercism/pharo-tooling

I've been using copyright `Exercism, Inc` and the MIT license by default, but if you have a preference for a different license, I'm cool with it as long as its open source and makes sense.

**Comment by bencoman** [comment]
Pharo's preferred licence is MIT.

**Comment by samWson** [comment]
I've pushed the _Exercism Exporter_ (for lack of a better name) to the repository, so everyone can see it now. I renamed the repository to `exercism-pharo-tooling`. While the name is a bit redundant, it keeps it the same as the package name in Pharo and makes it stand out better among all the other packages.

At the moment I'm going with the plan of making the export tool produce two files. One untouched file for sharing so that others can _file in_ the code into their image, and the other scrubbed free of meta data for displaying on Exercism.io. I've looked at using the Tonel file format, but all the existing tools for it seem to be designed to work on Iceberg or Monticello repositories, so I don't think I could get Tonel to work as a solution.

Once this export tool is done, I can really start to get to work on making the first few exercises.

**Comment by samWson** [comment]
Quick update: I'll track the actual implementation to this issue [here](https://github.com/exercism/exercism-pharo-tooling/issues/1).

**Comment by macta** [comment]
@samWson which repo have you pushed to? I'm not sure where to look.

I'm a bit puzzled by the conversation here though - as was mentioned in another thread - there is a Tonal format that Pharo uses for git - which is readable. In fact on my iPad I imported a TextMate theme for Smalltalk for one of the text editors and its possible to edit code in it (along with a git client) and make changes to smalltalk code (of course no refactoring etc - but simple stuff is fine).

Why can't we start structuring the project so HelloWorld smalltalk gives you a tonal file that you can edit by hand (and in fact you could run the tests from the command line with 

-st exercism.st

Where that script is something like:
```
l tonal |
tonal :=  'HelloWorld.class.st' asFileReference'.
(TonelReader on: tonel fileName: tonel path parent pathString ) loadDefinitions.
HelloWorldTest runAllAndLogResult
```

**Comment by macta** [comment]
@kytrinyx is there something that describes better what is going on with Exercism - when the cli client submits something, you must have some sort of rendering template - what does it look like/expect?What library do you use to render code examples (some support Smalltalk but might need tweaking for our newer Tonal format). Equally - how can we try a dry run of a Smalltalk HelloWorld example - i'd like to see what a submission looks like (to assess if Tonal is good enough to have a conversation around - which is my assumption). If we can establish this - I don't think the tooling to integrate it into our IDE is particularly big - and as I allude to - for the kinds of early examples i'm seeing, you could almost use VSCode and run Pharo commandline - which is sub-optimal but it lets us try out the conversation on code aspect.

**Comment by bencoman** [comment]
@samWson, same question as macta.
Neither https://github.com/exercism/pharo-tooling
nor https://github.com/exercism/exercism-pharo-tooling
seem to work.

btw, I can't remember if I mentioned it elsewhere,
before I noticed this thread, I had started investigating push/pull directly from inside Pharo.
https://github.com/bencoman/pharogui-exercism

But I don't have time to push it further for a couple of weeks.
The first iteration would be a command-line-oriented interface run from a Playground in Pharo,
and perhaps later providing a gui interface.

Since solutions may encompass multi classes, for consistency I think exercise downloads
and solution uploads should be done on a package-per-exercise basis. Packages will help keep the student's code organised within the Pharo IDE.

**Comment by macta** [comment]
For the record - to write out a HelloWorld like example (in its own package) in Tonel its simply:

```
TonelWriter new 
  sourceDir: '.' asFileReference; 
  writeSnapshot: (MCPackage named: HelloWorldTest package name) snapshot.
```
To read it back in:
```
tonelLocator := '*.st' asFileReference.
(TonelReader on: tonelLocator fileName: tonelLocator path parent pathString ) loadDefinitions.
```

A sample tonel file might look something like this (a bit verbose, but readable and commentable):
```
Class {
	#name : #HelloWorld,
	#superclass : #Object,
	#category : #HelloWorld
}

{ #category : #exercism }
HelloWorld class >> sayHello [

	^'Hello, World!'
]
```

**Comment by samWson** [comment]
@macta I like the quick guide on using `TonelWriter` in your comment. It's a much better solution than the thing I was working on over the last week.

**Comment by bencoman** [comment]
@samWson, With the links I provided above and also your link to @macta "This repo has been made" I get a github branded 404 error.  But why not make it open rather than bother with permissions?  It reduces the opportunities to gain contributors. 

I was only going to delete my repo after transferring it into a folder under the exercism-pharo-tooling repo.

btw, for a quick test, use an existing class...
TonelWriter new sourceDir: '.' asFileReference; 
    writeSnapshot: (MCPackage named: 'AST-Tests-Core') snapshot.

and review the result using File Browser from the world-menu.

**Comment by samWson** [comment]
@kytrinyx is there a reason for the [exercism-pharo-tooling](https://github.com/exercism/exercism-pharo-tooling) repo not to be public? @bencoman makes a good point above on reducing the opportunity to gain contributors. Making it public would also save me the trouble of vetting and adding collaborators.

**Comment by macta** [comment]
For the repo, if we can give Ben and I permissions it’s a start, but public would be better.

In the repo, do we mirror the setup of something like python? (Which project is the best example?).

Also how can we test a sample interaction - is there a sandbox? This is why I said to hand edit a few examples in plain Tonel so we can see how examples render on the site. Ben tells me the renderer should work.

Given how easy it is to save and read a pkg in Tonel, I do t think we will bother with the cmd line (but could add it as a nice extra to be old skool too). We can quickly get save/import running from a menu item and then add Bens idea to make it completely transparent as a second phase.

I think we could get something running in a few hours (spread over a few days I imagine).

The key is to have a sandbox.

I’m also not clear how more complex problems look in other languages - haven’t got that far in my python journey.

To me the end game would be to integrate GtDocumentor and show live exercism comments in our ide in the code (quite doable if our tools keep going the way it looks). But for now let’s play in the cli/files space and prove that first.

**Comment by samWson** [comment]
@macta @bencoman I've invited both of you as collaborators with admin permissions. I would have invited you both into the exercism-pharo team but even though I am the only member in the team, I bizarrely can't invite anyone else into it. @kytrinyx is this something you can help with? Hopefully being collaborators should let you do everything you need. Let me know if there are any more problems. 

@macta For an idea of how we are going to structure this repo, Exercism have made a good guide [here](https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md). Have a read of that if you haven't already. For this repo we will follow the already existing Exercism conventions as much as possible. We also have the [exercism-pharo-tooling repo](https://github.com/exercism/exercism-pharo-tooling) for any custom tools we need to make to integrate Pharo into the normal Exercism workflow. This is the repo I just invited you to as a collaborator.

@macta I like some of the ideas you have mentioned:
> To me the end game would be to integrate GtDocumentor and show live exercism comments in our ide in the code (quite doable if our tools keep going the way it looks). But for now let’s play in the cli/files space and prove that first.

This kind of integration would be a worthy goal. For now though lets just stick to a minimum viable product on the tooling side and get this language track working first. For now that means getting code out of the Pharo image and into a text file (Tonel), then send it to Exercism.io with the already existing command line tools.

**Comment by kytrinyx** [comment]
Sorry -- I'm catching up on about 6 weeks worth of notifications.

The pharo tooling repo should have been public, I didn't realize I had made it private by accident. I've made it public.

For rendering on the site we straight-up render the files that are submitted as UTF-8, using Prism (https://prismjs.com/) for syntax highlighting.

I think you should be able to use the existing CLI to submit to the site as it is now (`exercism submit file1 file2`), and it should give you a URL that will show you the result. If that doesn't work, then would you open an issue on https://github.com/exercism/exercism.io/issues so that we can discuss how to make a track available to maintainers and select beta testers while the track is being developed?

**Comment by macta** [comment]
This issue is more historical now (it’s a sort of Epic) might be able to close it once we’ve tested in beta status and tested some of the finer grained issues we have,

**Comment by macta** [comment]
I think we are beyond this one now. Closing to tidy up
